### ISSUE TITLE
Background doesn't load right on code output

### ISSUE THREAD

**Issue by Nidoskull** [cornetespoir/build-a-theme#1]
Hello! I've been playing with this theme builder, but I've noticed one small issue- when you export the code, and then set a background image, the background *color* takes precedence.

It's entirely possible that this is just a bad internet moment, as the image I used *is* quite large, but I've found that I could fix it manually by just swapping --background-image and --background around in the HTML.

I'm reporting this so that less code-savvy users can find the solution, and/or hopefully so this minor bug can be fixed on the exporting side!

**Comment by cornetespoir** [comment]
hi @Nidoskull ! 

Yea the background image definitely shouldn't be doing that! I've been unable to recreate the issue so far, though. The test blogs I'm using have all been able to add background images. 

Just want to make sure so I know how to approach the potential bug, were you using the built in options or editing the HTML to add the background image?

Here's what my test blog looked like when I added a background image:

![31IlfZVtfG](https://user-images.githubusercontent.com/35387318/212778374-008ca14e-5edf-414d-a173-9098184bf876.gif)

**Comment by Nidoskull** [comment]
I was using the built-in options, not the HTML. The only editing I did on that front was swapping those two bits around, haha!
I will note that it *did* look fine in the previewer, but when I saved the theme it was stuck to the color picked, not the background image.

**Comment by cornetespoir** [comment]
@Nidoskull I still wasn't able to reproduce the issue, but just to be safe I updated the CSS, so it should be good now!
